### ISSUE TITLE
A little wonky but very cool.

### ISSUE THREAD

**Issue by snbarnesaz** [josephrmartinez/AskYouTube#1]
A little wonky but very cool.

**Comment by josephrmartinez** [comment]
I apologize for the inconvenience! This was a personal learning project and a very wonky way to spin up a Chrome extension with a fastapi server making OpenAI requests. Running this project requires you to activate and run the fastapi server while you use the Chrome extension -- this is pretty unusual and not many people would go through the hassle to actually get this all running. It would be much nicer if I just set up and paid for the server myself. The problem here is that I would then be paying for every user's OpenAI requests and this could get out of control. So I built this repository in a way that someone could run the project on their own machine and just incur the costs of the OpenAI requests and not have to pay a monthly subscription. 

I've updated the README to better explain exactly how to correctly set the environmental variables and spin up the fastapi server. 

Again, I'm really sorry for the frustration caused by this!

**Comment by snbarnesaz** [comment]
Thank you for the help and I apologize for all the complaining. I edited or deleted my comments on Youtube (and here in Github). Sorry to hear you were dealing with a medical issue. Thanks for your contributions.

**Comment by josephrmartinez** [comment]
Your comments were not a problem at all! I really appreciate you pointing out that the instructions were not clear. I run into issues all the time with poor documentation. (Currently banging my head against a wall trying to figure out simple auth with Next.js and Supabase -- this should be super simple but there are definitely gaps in the docs.) Even though this was a simple learning project for me, I should have really made an effort to better document the installation process without making any assumptions. I'm grateful that you pointed it out!
